"""add_profile_image_path_to_users

Revision ID: 71d7f2a38428
Revises: 50d91da33024
Create Date: 2026-06-02 22:08:04.554937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71d7f2a38428'
down_revision: Union[str, None] = '50d91da33024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image_path')
    # ### end Alembic commands ###
